### ISSUE TITLE
Where is partial content check?

### ISSUE THREAD

**Issue by amichair** [mnot/redbot#160]
The about page mentions that RED checks, among other things, partial content.

However, there is no mention of partial content or ranges in the results when testing a page, nor in the har, nor in the docs or anywhere else that I can find. Perhaps I'm missing something, but then maybe it should be mentioned more explicitly somewhere.

Thanks for the great tool!

**Comment by mnot** [comment]
Works for me, e.g.,:
  https://redbot.org/?uri=http%3A%2F%2Fhttpd.apache.org%2F

Are you sending `Accept-Ranges: bytes` in your responses?

Cheers,

**Comment by amichair** [comment]
You're right, Accept-Ranges is not being sent. However, the RFC says it MAY be sent (not even SHOULD), and a client MAY generate range requests without having received this header - so perhaps you can check for it anyway, even if the header is not sent in the response?

I figured since ranges are not used that often, it might be better not to send Accept-Ranges with every response, to save on resources. Do you think that's reasonable? Also, it would make sense that a client would try to get a range if it needs one without first 'wasting' a request just to see if the response would contain Accept-Ranges.

If it is indeed required to send Accept-Ranges, would that be only with a 200 response?

**Comment by mnot** [comment]
It's not required to send `Accept-Ranges`, but it is a good hint that the resource supports partial content. You can discover that by other means too, but at the moment there isn't any standard way to do it other than `Accept-Ranges`.

It's certainly reasonable not to always send it; e.g., on my personal server, I strip `Accept-Ranges` from all responses except for PDFs and videos (IIRC).

I'm not against having REDbot do this test even when `Accept-Ranges` is not there, but I'm not inclined to add an option to the Web UI to do this, because it'll quickly get *very* cluttered.

**Comment by amichair** [comment]
I don't think a UI option to test for this is necessary... you can just always test for it and report in the results whether it is supported or not. If it supported but behaving incorrectly, that would show up as an error.
