### ISSUE TITLE
Date header incorrectly flagged as late

### ISSUE THREAD

**Issue by fgm** [mnot/redbot#203]
Currently REDbot warns when the Date: header in a response is in the past.

However, from the combination of:

- https://tools.ietf.org/html/rfc7231#section-7.1.1.2 defining it
- https://tools.ietf.org/html/rfc5322#section-3.6.1 specifying some more semantics
- https://tools.ietf.org/html/rfc7234#section-4 defining its usage in age calculations

It seems emitting a response in the past is a perfectly normal situation, especially when the server is actually a cache, because the Date header is supposed to represent the date the message was originated, not the time it was transmitted to the client. This is a situation which can happen with any application including an internal proxy/cache.

One way to estimate this is the actual behavior being observed and not an actual time error on the server could be to perform two requests at 1 second interval and compare dates: if the Date header changes by 1 second (possibly controlled by the variation of other headers like Age if present), then the server is indeed late. But if the Date header does not change while other time-related headers do, then it is probably representing the orig-date of a cached message, and is not in error.

**Comment by mnot** [comment]
Do you have an example URL? REDbot only warns when the Date header is in the past and the Age header doesn't reflect the delta between now and that time (with some forgiveness for minor clock sync issues, etc.).

**Comment by FGM** [comment]
I noticed this on https://redbot.org/?uri=https%3A%2F%2Fblog.riff.org%2F

Apparently it also happens if there is no Age: header, which AIUI can happen if there was a cache validation (https://tools.ietf.org/html/rfc7234#section-5.1): the Age header is only needed if there was no validation before serving the response. This is the case here (Drupal 8 CMS internal page cache performs validation).

**Comment by FGM** [comment]
That's something I missed in the RFCs: do you have a pointer to it ?

**Comment by mnot** [comment]
See:
  http://httpwg.org/specs/rfc7234.html#freshening.responses

**Comment by FGM** [comment]
Yes that's the same paragraph I pointed to. But for one thing it does not mention the Date header, for the other it only applies in the http pull validation model, whereas this internal cache, pretty much like Varnish with xkey, uses push (in)validations, so there is no upstream validation request which could return a 304 anyway. This is why Varnish switched to serving the old Date header value in https://github.com/varnishcache/varnish-cache/commit/89870e0bbd785964c322e1e453f492d747731c88

**Comment by mnot** [comment]
To be useful for the caching model, the Date header has to reflect the time the message was originated; HTTP only accounts for time in a HTTP cache as a way to "pause" that (effectively). If the Date isn't correct, it throws off freshness calculations (which is why REDbot complains).

PHK has strong feelings about Varnish *not* being a HTTP cache (in the specified sense), which is at least a coherent argument (although I don't agree with it); however, it doesn't give Varnish a free pass to not generate correct Date headers as an origin server.
