### ISSUE TITLE
Strange HTTP/503!

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#218]
https://redbot.org/?uri=http%3A%2F%2Fwww.papiron.hu%2F

Version 71.0.3578.98 (Official Build) (64-bit) on Windows 10 latest

![kep](https://user-images.githubusercontent.com/952007/52651011-af045600-2eeb-11e9-8269-6b4ee5131651.png)

BTW https://redbot.org/static/logo/favicon-32x32.png works OK

**Comment by mnot** [comment]
Can't reproduce; is this still happening?

**Comment by szepeviktor** [comment]
Today after 2×default and 2×Content Negotiation fetches it stops without a message.

**Comment by mnot** [comment]
Hi! Sorry for taking so long; I only sometimes have time to work on redbot.

It turns out that this was happening because the response is so large, and processing the response body to display it took so much CPU that the watchdog forced redbot to restart.

I've reduced the body sample size; it seems to be working fine now.

Thanks for your patience.
