### ISSUE TITLE
Website: Add alternative (passive) modes to fetching a URL (textarea, HAR input, query string)

### ISSUE THREAD

**Issue by jakub-g** [mnot/redbot#290]
https://redbot.org/ is very nice (I love it), but it has a few problems:

- it does not work for intranet resources (once could set up a local clone of course)
- it only works for things that are already deployed to some URL and serving HTTP responses.

Possible improvements that would make it more useful:

- HAR input (#262)
- Having a `<textarea>` (apart from the dropdown) where one could copy-paste arbitrary newline-separate headers obtained from browser devtools, curl etc., to allow free play and understand "what will happen if I do X"
- What would make redbot ultimately useful though would be integration with browsers' devtools. It could be as simple as making `uri` param optional and letting devtools construct a URL to redbot with the existing `req_hdr=...&req_hdr=...` somewhere in the network panel (I'm unsure though how likely devtools vendors would be to ship such link).

**Comment by mnot** [comment]
FWIW - there is now Slack support; see https://redbot.org/slack/

I don't think that dev tools integration is practical; they're not going to want to call out to a server -- it'd be better to rewrite it as JS.

However, I've been thinking about factoring out the tests that don't require making new requests into a separate library, so that it can be used from the command line / other tools more easily. I suppose one that that could be run as WASM in a browser too...

**Comment by mnot** [comment]
See mnot/httplint. Closing this as I don't think these should be redbot UX - redbot focuses on live testing of resources.
