### ISSUE TITLE
REDbot stopped showing green okay messages

### ISSUE THREAD

**Issue by szepeviktor** [mnot/redbot#322]
Could it be that ✅ green okay messages are hidden?
How to show them again?

https://redbot.org/?uri=https://redbot.org/

![image](https://github.com/mnot/redbot/assets/952007/79a9f587-5a04-4a4e-9623-55e19697c388)

**Comment by szepeviktor** [comment]
On CLI good-old messages are displayed.
```
* General:
  * The server's clock is correct.

* Caching:
  * This response allows all caches to store it.
  * This response is fresh until 5 sec from now.
  * This response may still be served by a cache once it becomes stale.
```

**Comment by mnot** [comment]
This was a very interesting bug. The immediate cause was CSP nonces failing, because two of them didn't match. That was because the nonce value was set by updating the Jinja template globals, which created a race condition -- if another request came in while the response was being processed, it would overwrite the globals (including the nonce value). 

This was especially apparent when testing a resource on the same box -- e.g. redbot.org or mnot.net from redbot.org. The reverse proxy that I have in front of them made it more likely to trigger the race condition.

The commit above should fix it, but I won't close until it's more sure (initial testing seems promising).

**Comment by szepeviktor** [comment]
Thank you.
